#define DFU_CIPHER _DISABLE
#define DFU_INTF_EEPROM _DISABLE
#define DFU_DNLOAD_NOSYNC _DISABLE
#define DFU_DBLRESET_MS _DISABLE
#define DFU_STR_MANUF "KMZ Brno I"
#define DFU_STR_PRODUCT "MTB-USB v4 bootloader"
#define DFU_BOOTSTRAP_GPIO _DISABLE
#define DFU_APP_START 0x1000
